name: Go package

on: [ push ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Install dependencies
        run: go get .

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./... -coverprofile=./cover.out

      - name: Test Coverage
        id: coverage
        uses: vladopajic/go-test-coverage@v2
        with:
          profile: cover.out
          local-prefix: github.com/lezhnev74/go-iterators
          threshold-file: 80
          threshold-package: 80
          threshold-total: 95

      - name: Go Coverage Badge
        uses: tj-actions/coverage-badge-go@v2.4.1

#      - name: make coverage badge
#        uses: action-badges/core@0.2.2
#        if: contains(github.ref, 'main')
#        with:
#          label: coverage
#          message: ${{ steps.coverage.outputs.badge-text }}
#          message-color: ${{ steps.coverage.outputs.badge-color }}
#          file-name: coverage.svg
#          badge-branch: badges
#          github-token: "${{ secrets.GITHUB_TOKEN }}"